language: bash
stages:
- foo
- bar
- ting
jobs:
  include:
  - stage: foo
    name: "Foo Job"
    script: echo "Job foo task"
  - stage: bar
    name: "Bar job 1"
    script: echo "Job bar task 1"
  - stage: bar
    name: "Bar job 2"
    script: echo "Job bar task 2"
foo:
  - echo "Global foo task"
bar:
  - echo "Global bar task"
ting:
  - echo "Global ting task"